In [37]:
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [39]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [40]:
voc_size=10000

In [41]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[51, 5162, 3908, 8036],
 [51, 5162, 3908, 7004],
 [51, 6, 3908, 7177],
 [4222, 4580, 5789, 4285, 943],
 [4222, 4580, 5789, 4285, 7493],
 [5053, 51, 4456, 3908, 1630],
 [2981, 1144, 357, 4285]]

In [42]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [43]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre', maxlen=sent_length)
print(embedded_docs)
dim=10

[[   0    0    0    0   51 5162 3908 8036]
 [   0    0    0    0   51 5162 3908 7004]
 [   0    0    0    0   51    6 3908 7177]
 [   0    0    0 4222 4580 5789 4285  943]
 [   0    0    0 4222 4580 5789 4285 7493]
 [   0    0    0 5053   51 4456 3908 1630]
 [   0    0    0    0 2981 1144  357 4285]]


In [44]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [45]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [46]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 45ms/step


array([[[-0.03996844,  0.03201187, -0.04123423, -0.04631234,
         -0.01943189,  0.0312933 ,  0.04402618, -0.04258334,
         -0.01111996, -0.03717964],
        [-0.03996844,  0.03201187, -0.04123423, -0.04631234,
         -0.01943189,  0.0312933 ,  0.04402618, -0.04258334,
         -0.01111996, -0.03717964],
        [-0.03996844,  0.03201187, -0.04123423, -0.04631234,
         -0.01943189,  0.0312933 ,  0.04402618, -0.04258334,
         -0.01111996, -0.03717964],
        [-0.03996844,  0.03201187, -0.04123423, -0.04631234,
         -0.01943189,  0.0312933 ,  0.04402618, -0.04258334,
         -0.01111996, -0.03717964],
        [ 0.01646454,  0.01659811,  0.04855699, -0.02431219,
         -0.00637866, -0.0375868 ,  0.00074707, -0.0374824 ,
         -0.02839178, -0.02987777],
        [-0.04712533, -0.02558603, -0.02678384, -0.02471982,
          0.02001823,  0.03795724,  0.04136914,  0.01050937,
          0.03023871,  0.03011325],
        [ 0.02902905, -0.01720186, -0.03162142, -0.0

In [47]:
embedded_docs[0]


array([   0,    0,    0,    0,   51, 5162, 3908, 8036])

In [48]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [ 0.01646454,  0.01659811,  0.04855699, -0.02431219, -0.00637866,
        -0.0375868 ,  0.00074707, -0.0374824 , -0.02839178, -0.02987777],
       [-0.04712533, -0.02558603, -0.02678384, -0.02471982,  0.02001823,
         0.03795724,  0.04136914,  0.01050937,  0.03023871,  0.03011325],
       [ 0.02902905, -0.01720186, -0.03162142, -0.00711249, -0.02988541,
         0.03924665,  0.01356727,  0.04917568

In [49]:
model.predict(embedded_docs[1])

1/1 [==============================] - 0s 21ms/step


array([[-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [-0.03996844,  0.03201187, -0.04123423, -0.04631234, -0.01943189,
         0.0312933 ,  0.04402618, -0.04258334, -0.01111996, -0.03717964],
       [ 0.01646454,  0.01659811,  0.04855699, -0.02431219, -0.00637866,
        -0.0375868 ,  0.00074707, -0.0374824 , -0.02839178, -0.02987777],
       [-0.04712533, -0.02558603, -0.02678384, -0.02471982,  0.02001823,
         0.03795724,  0.04136914,  0.01050937,  0.03023871,  0.03011325],
       [ 0.02902905, -0.01720186, -0.03162142, -0.00711249, -0.02988541,
         0.03924665,  0.01356727,  0.04917568